"""Add questionnaire_url to Club

Revision ID: 3e91c5e17135
Revises: f613ea1968c4
Create Date: 2025-07-25 10:58:59.833023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e91c5e17135'
down_revision: Union[str, Sequence[str], None] = 'f613ea1968c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('questionnaire_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clubs', 'questionnaire_url')
    # ### end Alembic commands ###
