"""add_image_url_columns

Revision ID: 843dc97f5ce4
Revises: ddc75cf1374e
Create Date: 2025-07-27 00:05:04.071042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '843dc97f5ce4'
down_revision: Union[str, Sequence[str], None] = 'ddc75cf1374e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('events', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'image_url')
    op.drop_column('clubs', 'image_url')
    # ### end Alembic commands ###
