"""Add sheet_id and range_name to Club

Revision ID: cc9d5d9f3e25
Revises: c40a28bbd129
Create Date: 2025-07-24 10:48:02.529325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc9d5d9f3e25'
down_revision: Union[str, Sequence[str], None] = 'c40a28bbd129'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('sheet_id', sa.String(), nullable=True))
    op.add_column('clubs', sa.Column('range_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clubs', 'range_name')
    op.drop_column('clubs', 'sheet_id')
    # ### end Alembic commands ###
