"""add role to membership

Revision ID: ddc75cf1374e
Revises: 098e0e582028
Create Date: 2025-07-26 16:08:49.911615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'ddc75cf1374e'
down_revision: Union[str, Sequence[str], None] = '098e0e582028'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    membershiprole = postgresql.ENUM('member', 'moderator', name='membershiprole')
    membershiprole.create(op.get_bind())
    # Add the column as nullable first
    op.add_column('memberships', sa.Column('role', sa.Enum('member', 'moderator', name='membershiprole'), nullable=True))
    # Set default value for existing rows
    op.execute("UPDATE memberships SET role='member'")
    # Alter the column to be NOT NULL
    op.alter_column('memberships', 'role', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    membershiprole = postgresql.ENUM('member', 'moderator', name='membershiprole')
    membershiprole.drop(op.get_bind())
    op.drop_column('memberships', 'role')
    # ### end Alembic commands ###
