"""Add sheet_id and range_name to Club

Revision ID: f613ea1968c4
Revises: cc9d5d9f3e25
Create Date: 2025-07-24 11:07:01.557428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f613ea1968c4'
down_revision: Union[str, Sequence[str], None] = 'cc9d5d9f3e25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
